### ISSUE TITLE
Option to keeping the original file

### ISSUE THREAD

**Issue by stingray21** [tarampampam/tinifier#103]
Could add a flag for an output folder or output filename or something similar. Basically and option to keep the original file. 

PS: Thank you, I love the tool

**Comment by tarampampam** [comment]
Sorry for the late response. Changes in #108 are what you need, or not?

**Comment by stingray21** [comment]
Yes, thank you!!! Much appreciated

**Comment by tarampampam** [comment]
@ciro-mota Sorry for the long wait - the `--keep-original-file` option has been added back as you requested. It was included in the recently published v5.1.0 release

**Comment by ciro-mota** [comment]
> [@ciro-mota](https://github.com/ciro-mota) Sorry for the long wait - the `--keep-original-file` option has been added back as you requested. It was included in the recently published [v5.1.0](https://github.com/tarampampam/tinifier/releases/tag/v5.1.0) release

Thank you so much for responding to my request and bringing this option back. It's a very important part of my image workflow.
