### ISSUE TITLE
Compiling on WSL2 Ubuntu

### ISSUE THREAD

**Issue by DanKrue80** [tarampampam/tinifier#11]
Hey there,

following the instructions from your README, `make test` and `make build` don't work properly under Ubuntu on Windows 10 (WSL2).

Output on `make test`:
```
▸  make test
/bin/sh: 1: run: not found
make: *** [Makefile:36: test] Error 127
```

Output on `make build`:
```
▸  make build
run --rm --user "1000:1000" app go build -ldflags="-s -w" -o '/build/tinifier' .
/bin/sh: 1: run: not found
make: *** [Makefile:30: build] Error 127
```

![Anmerkung 2020-06-18 110453](https://user-images.githubusercontent.com/39704296/85001131-921d0a00-b153-11ea-85b2-03fbb5634385.jpg)

Hoping for your good news soon.

Best
Daniel

**Comment by tarampampam** [comment]
Hi! Just install `docker` - `curl -SsL get.docker.com | sudo sh`
