### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by jerryc127** [tarampampam/tinifier#6]
### Is your feature request related to a problem?

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

### Describe the solution you'd like

> A clear and concise description of what you want to happen.

## Additional context

> Add any other context about the feature request here.

I try to download the window exe in the release page and install,
but it just flash across and i don't know it success or not。
i try to use tinifier in power shell, but it show unknown

**Comment by tarampampam** [comment]
What you see after execution `tinifier.exe -k 'YOUR-API-KEY-GOES-HERE' image.png`?

**Comment by jerryc127** [comment]
![image](https://user-images.githubusercontent.com/16351105/70985466-264fdb00-20f7-11ea-95d6-11c66564ac0e.png)

it doesn't work..

it need to install something before ?

**Comment by tarampampam** [comment]
No. Very strange.. Can you show error message in english?

**Comment by jerryc127** [comment]
it work. thx

![image](https://user-images.githubusercontent.com/16351105/71006834-f1f11480-2120-11ea-8f80-063bb9135c75.png)
