### ISSUE TITLE
Can i apply more than 10 KEY?

### ISSUE THREAD

**Issue by zzusec** [tarampampam/tinifier#63]
Can i apply more than 10 KEY with Batch compress? How can i do it ?

**Comment by tarampampam** [comment]
```
tinifier compress -k 'key1' -k 'key2' ... ./images-directory 
```

Is that what you asked?

**Comment by zzusec** [comment]
Yes ---- Replied Message ***@***.***>Date09/18/2021 12:51 ***@***.***> ***@***.******@***.***>SubjectRe: [tarampampam/tinifier] Can i apply more than 10 KEY? (#63)
tinifier compress -k 'key1' -k 'key2' ... ./images-directory  

Is that what you asked?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/tarampampam/tinifier/issues/63#issuecomment-922184061",
"url": "https://github.com/tarampampam/tinifier/issues/63#issuecomment-922184061",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
