### ISSUE TITLE
Compiling for macOS?

### ISSUE THREAD

**Issue by OwenMelbz** [tarampampam/tinifier#7]
Hi, the releases don't contain any macOS versions, wondering if it's compatible?

When you run `make build` it just throws an error

```
➜ make build
run --rm --user "501:20" app go build -ldflags="-s -w" -o '/build/tinifier' .
/bin/sh: run: command not found
make: *** [build] Error 127
```

Thanks!

**Comment by tarampampam** [comment]
Done! https://github.com/tarampampam/tinifier/releases

**Comment by OwenMelbz** [comment]
Awesome thanks :) appreciate the speed response!
