### ISSUE TITLE
Go installation issue

### ISSUE THREAD

**Issue by stingray21** [tarampampam/tinifier#91]
I'm very interested and excited to use this application, however I have some issues trying to install it with `go get`

```shell
> go get -u github.com/tarampampam/tinifier/v3       
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
 
> go install github.com/tarampampam/tinifier/v3@latest
go: github.com/tarampampam/tinifier/v3@latest: module github.com/tarampampam/tinifier/v3@latest found (v3.5.0), but does not contain package github.com/tarampampam/tinifier/v3
```

**Comment by tarampampam** [comment]
Can I close this issue?

**Comment by stingray21** [comment]
I apologize if this is a stupid question, but I am very new to Go. 

I'd like to use your application as CLI. So if I understood you correctly I just download the compiled version and make it an executable?

If that's the case, you can close the issue.

**Comment by tarampampam** [comment]
Yes, sure! But, if you want to compile the binary file by yourself, you can download the sources (`git clone ....`) and execute something like this: `CGO_ENABLED=0 go build -trimpath -ldflags "-s -w" -o ./tinifier ./cmd/tinifier/`
