### ISSUE TITLE
Support resize feature ?

### ISSUE THREAD

**Issue by abcfy2** [tarampampam/tinifier#92]
Tinypng supports resizing image: https://tinypng.com/developers/reference#resizing-images

Would you please support this feature?

**Comment by tarampampam** [comment]
In the go package or cli?

**Comment by abcfy2** [comment]
cli please. Thanks.

**Comment by tarampampam** [comment]
> Resizing counts as one additional compression. For example, if you upload a single image and retrieve the optimized version plus 2 resized versions this will count as 3 compressions in total.

So, I think the better strategy would be image resizing **before** compressing using any other tool (of which there is an enormous number).

Sorry, but at this moment I don't see much point in this feature.
